[project]
name = "finops-lite"
version = "0.0.1"
description = "Beginner-friendly AWS FinOps dashboard for cost and tag hygiene"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["boto3>=1.34"]

[project.scripts]
finops-lite = "finops_lite.cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["finops_lite*"]
