[project]
name = "finops-lite"
version = "0.0.1"
description = "Beginner-friendly AWS FinOps dashboard for cost and tag hygiene"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
finops-lite = "finops_lite.cli:main"
