name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install boto3
          pip show finops-lite || true
          pip list | grep finops || true

      - name: Smoke import
        run: |
          python - <<'PY'
          import sys
          print("sys.path:", sys.path)
          import finops_lite, importlib
          importlib.import_module("finops_lite.cli")
          print("import_ok:", getattr(finops_lite, "__file__", "<no-file-attr>"))
          PY
