name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          # safety net in case packaging deps are missed
          pip install boto3

      - name: Smoke import
        run: |
          python - <<'PY'
          import importlib
          importlib.import_module("finops_lite")
          importlib.import_module("finops_lite.cli")
          print("import_ok")
          PY

      - name: CLI --help
        run: |
          python -m finops_lite.cli --help
          python -m finops_lite.cli services --help
