name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      # Zero-AWS smoke checks so CI always runs without credentials
      - name: Smoke tests
        run: |
          python - <<'PY'
          import importlib
          importlib.import_module("finops_lite")
          print("import_ok")
          PY
          python -m finops_lite.cli --help
          python -m finops_lite.cli services --help
